WebApp2/Controllers/DonController.cs
using Fr.EQL.AI110.DLD_GE.Business;
using Fr.EQL.AI110.DLD_GE.Entities;
using Microsoft.AspNetCore.Mvc;
using Fr.EQL.AI110.DLD_GE.WebApp2.Models;



namespace Fr.EQL.AI110.DLD_GE.WebApp2.Controllers
{
    public class DonController : Controller
    {
        public int controller;
        // 0 : Créer don à domicile
        // 1 : Créer don chez un partenaire ou box
        // 2 : Don recherché
        // 3 : Don reservé

        private CreateDonViewModel Model { get; set; }
        // Permet choix de l'adherent connecté
        [HttpGet]
        public IActionResult Index()
        {
            CreateDonViewModel model = new CreateDonViewModel();

            AdherentBusiness adhBU = new AdherentBusiness();
            model.Adherents = adhBU.GetAdherents();

            return View(model);
        }
        [HttpPost]
        public IActionResult Index(CreateDonViewModel model)
        {
            DonBusiness bu = new DonBusiness();
            model.DonDetails = bu.GetAllDonsFromIdAdh(model.SelectedAdherent.Idadh);

            AdherentBusiness adhBU = new AdherentBusiness();
            model.SelectedAdherent = adhBU.GetAdherentbyId(model.SelectedAdherent.Idadh);

            return View("DisplayDon", model);
        }

        [HttpGet]
        public IActionResult Edit()
        {
            CreateDonViewModel model = new CreateDonViewModel();

            AdherentBusiness adhBU = new AdherentBusiness();
            model.Adherents = adhBU.GetAdherents();

            return View(model);
        }

        [HttpPost]
        public IActionResult CatchAdherent(CreateDonViewModel model)
        {
            AdherentBusiness adhBU = new AdherentBusiness();
            model.SelectedAdherent = adhBU.GetAdherentbyId(model.SelectedAdherent.Idadh);

            CategorieBusiness catBU = new CategorieBusiness();
            model.Categories = catBU.GetCategories();

            return View("ChooseCategory", model);
        }

        [HttpPost]
        public IActionResult CatchCategory(CreateDonViewModel model)
        {
            AdherentBusiness adhBU = new AdherentBusiness();
            model.SelectedAdherent = adhBU.GetAdherentbyId(model.SelectedAdherent.Idadh);

            CategorieBusiness catBU = new CategorieBusiness();
            model.SelectedCategorie = catBU.GetCategorieById(model.SelectedCategorie.IdCategorie);

            SouscategorieBusiness subCatBU = new SouscategorieBusiness();
            model.SousCategories = subCatBU.GetAllSousCategoriesById(model.SelectedCategorie.IdCategorie);

            return View("ChooseSubCategory", model);
        }
        [HttpPost]
        public IActionResult CatchSubCategory(CreateDonViewModel model)
        {
            AdherentBusiness adhBU = new AdherentBusiness();
            model.SelectedAdherent = adhBU.GetAdherentbyId(model.SelectedAdherent.Idadh);

            CategorieBusiness catBU = new CategorieBusiness();
            model.SelectedCategorie = catBU.GetCategorieById(model.SelectedCategorie.IdCategorie);

            SouscategorieBusiness souscategorieBusiness = new SouscategorieBusiness();
            model.SelectedSousCategorie = souscategorieBusiness.GetSousCategorieById(model.SelectedSousCategorie.IdSousCategorie);

            ProduitBusiness produitBusiness = new ProduitBusiness();
            model.Produits = produitBusiness.GetProduitsById(model.SelectedSousCategorie.IdSousCategorie);

            return View("ChooseProduct", model);
        }
        public IActionResult CatchProduct(CreateDonViewModel model)
        {
           
            AdherentBusiness adhBU = new AdherentBusiness();
            model.SelectedAdherent = adhBU.GetAdherentbyId(model.SelectedAdherent.Idadh);

            CategorieBusiness catBU = new CategorieBusiness();
            model.SelectedCategorie = catBU.GetCategorieById(model.SelectedCategorie.IdCategorie);

            SouscategorieBusiness souscategorieBusiness = new SouscategorieBusiness();
            model.SelectedSousCategorie = souscategorieBusiness.GetSousCategorieById(model.SelectedSousCategorie.IdSousCategorie);

            ProduitBusiness produitBusiness = new ProduitBusiness();
            model.SelectedProduit = produitBusiness.GetProduitById(model.SelectedProduit.IdProduit);

            UniteBusiness uniteBusiness = new UniteBusiness();
            model.Unites = uniteBusiness.GetUnitesByIdProduit(model.SelectedProduit.IdProduit);

            return View("ChooseUnity", model);
    }
        [HttpPost]
        public IActionResult Edit (CreateDonViewModel model, int id)
        {

                AdherentBusiness adhBU = new AdherentBusiness();
                model.SelectedAdherent = adhBU.GetAdherentbyId(model.SelectedAdherent.Idadh);
                model.Idemplacementstockage = id;
                DonBusiness donBusiness = new DonBusiness();
                Don don = new Don();
                don.IdAdh = model.SelectedAdherent.Idadh;
                don.IdUnite = model.SelectedUnity.IdUnite;
                don.IdProduit = model.SelectedProduit.IdProduit;

                don.Quantite = model.Don.Quantite;
                don.DateLimite = model.Don.DateLimite;
                don.DateAjout = DateTime.Now;
                if (model.Idemplacementstockage != 0)
                    {
                        don.IdEmplacementStockage = model.Idemplacementstockage;
                    }
                if (don.IdEmplacementStockage == 0) 
                {
                    don.IdVille = model.SelectedAdherent.Idville;
                    don.NumRue = model.SelectedAdherent.Numrue;
                    don.LibeleVoie = model.SelectedAdherent.Libelevoie;
                    don.DateDepotStockage = DateTime.Now;

            }
            if (don.IdEmplacementStockage != 0) 
                {
                    don.IdVille = model.Idville;
                    don.NumRue = model.Numrue;
                    don.LibeleVoie = model.Libelevoie;
                    
                }
            donBusiness.SaveDon(don);
            return View("EditConfirm");
         
        }
        [HttpGet]
        public IActionResult ChoixAvantDepotAdresse(CreateDonViewModel model)
            {
                this.Model = model;
                return View(Model); 
        }

        [HttpPost]
        public IActionResult ChoixAvantDepotAdresse(CreateDonViewModel model, int id)
            {
            this.Model = model;
            VilleBusiness vBU = new VilleBusiness();
            model.Villes = vBU.GetVilles();
            InfrastockageBusiness infBU = new InfrastockageBusiness();
            model.InfrastockageDetails = infBU.ToutInfraDispo();
            return View(Model) ; 
        }

        [HttpGet]
        public IActionResult IndexInfraParVille(CreateDonViewModel model)
        {
            this.Model = model;
            VilleBusiness vBU = new VilleBusiness();
            Model.Villes = vBU.GetVilles();

            InfrastockageBusiness infBU = new InfrastockageBusiness();
            Model.InfrastockageDetails = infBU.ToutInfraDispo();
            return View(Model);
        }
        [HttpPost]
        public IActionResult IndexInfraParVille(CreateDonViewModel model, string no)
        {
            this.Model = model;
            VilleBusiness vBU = new VilleBusiness();
            Model.Villes = vBU.GetVilles();

            InfrastockageBusiness infBU = new InfrastockageBusiness();
            Model.InfrastockageDetails = infBU.ToutInfraDispoParVille(Model.Idville);

            return View(Model);
        }

        [HttpPost]
        public IActionResult InfoEmplacementPartenaire(CreateDonViewModel model,int id)
        {   
            //CreateDonViewModel Model = (CreateDonViewModel)TempData["ParametreProposeDon"];
            this.Model = model;
            EmplacementstockageBusiness empBU = new EmplacementstockageBusiness();
            Model.empsDetails = empBU.ListEmplacementDispoInfra(id);

            return View(Model);
        }
        [HttpPost]
        public IActionResult AdresseDepotEnrgistrement(CreateDonViewModel model,int id)
        {
            this.Model = model;
            Model.Idemplacementstockage = id;

        //}

            return View("EditConfirm",Model);

        }

        [HttpGet]
        public IActionResult InfosDon(int id, int controller)
        {

            DonDetailsViewModel details = new DonDetailsViewModel();

            // controller à fournir dans la méthode appelante
            details.ControllerOrigine = controller;
            details.Id = id;

            DonBusiness biz = new DonBusiness();
            details.DonDetails = biz.ShowDetails(id);

            return View(details);
        }
        public IActionResult DisplayDonFromAdh(int id)
        {
            DonBusiness bu = new DonBusiness();
            CreateDonViewModel model = new CreateDonViewModel();
            model.DonDetails = bu.GetAllDonsFromIdAdh(id);

            foreach (DonDetails d in model.DonDetails)
            {
                d.TimeUntilExpiration = d.DateLimite - DateTime.Now;
                d.DurationDays = d.TimeUntilExpiration.TotalDays;
            }

            AdherentBusiness adhBU = new AdherentBusiness();
            model.SelectedAdherent = adhBU.GetAdherentbyId(id);

            return View("DisplayDon", model);
        }
        public IActionResult ConfirmationAnnulation(int id)
        {
            DonBusiness biz = new DonBusiness();
            biz.CancelDon(id, DateTime.Now);
            return View();
        }
    }
}

WebApp2/Controllers/PartenaireController.cs
using Microsoft.AspNetCore.Mvc;
using Fr.EQL.AI110.DLD_GE.Business;
using Fr.EQL.AI110.DLD_GE.Entities;
using Fr.EQL.AI110.DLD_GE.WebApp2.Models;

namespace Fr.EQL.AI110.DLD_GE.WebApp2.Controllers
{
    public class PartenaireController : Controller
    {
        private CreateDonViewModel Model { get; set; }
        [HttpGet]
        public IActionResult IndexPartenaireParVille()
        {
            PartenaireDetails model = new PartenaireDetails();

            VilleBusiness vBU = new VilleBusiness();
            model.Villes = vBU.GetVilles();

            PartenaireBusiness parBU = new PartenaireBusiness();
            model.PartenairesDetails = parBU.ToutPartenaireDetails();

            return View(model);
        }
        [HttpPost]
        public IActionResult IndexPartenaireParVille(PartenaireDetails model)
        {

            VilleBusiness vBU = new VilleBusiness();
            model.Villes = vBU.GetVilles();
            PartenaireBusiness partBU = new PartenaireBusiness();
            model.PartenairesDetails = partBU.ToutPartenaireParVille(model.Idville);
            return View(model);
        }
        
        public IActionResult InfoEmplacementPartenaire(int id)
        {
            
            EmplacementstockageBusiness empBU = new EmplacementstockageBusiness();
            List<EmplacementstockageDetails> model = empBU.ListEmplacementParPart(id);

            return View(model);

        }
       
        [HttpGet]
        public IActionResult IndexInfraParVille(CreateDonViewModel model)
        {
            this.Model = model;
            VilleBusiness vBU = new VilleBusiness();
            model.Villes = vBU.GetVilles();

            InfrastockageBusiness infBU = new InfrastockageBusiness();
            model.InfrastockageDetails = infBU.ToutInfraDispo();
            return View(model);
        }
        [HttpPost]
        public IActionResult IndexInfraParVille(CreateDonViewModel model, int id)
        {
            this.Model = model;
            VilleBusiness vBU = new VilleBusiness();
            model.Villes = vBU.GetVilles();

            InfrastockageBusiness infBU = new InfrastockageBusiness();
            model.InfrastockageDetails = infBU.ToutInfraDispoParVille(model.Idville);
            return View(model);
        }
    }
}

WebApp2/Controllers/RechercheController.cs
using Fr.EQL.AI110.DLD_GE.Business;
using Fr.EQL.AI110.DLD_GE.Entities;
using Microsoft.AspNetCore.Mvc;
using Fr.EQL.AI110.DLD_GE.WebApp2.Models;

namespace Fr.EQL.AI110.DLD_GE.WebApp2.Controllers
{
    public class RechercheController : Controller
    {
        [HttpGet]
        public IActionResult RechercheDonMultiCri()
        {
            // récupérer le modele
            DonRechercheViewModel model = new DonRechercheViewModel();

            CategorieBusiness catBU = new CategorieBusiness();
            model.Categories = catBU.GetCategories();


            SouscategorieBusiness souscatBU = new SouscategorieBusiness();
            model.Souscategories = souscatBU.GetSousCategories();

            ProduitBusiness prodBU = new ProduitBusiness();
            model.Produits = prodBU.GetProduits();

            VilleBusiness villeBU = new VilleBusiness();
            model.Villes = villeBU.GetVilles();

            // charger la vue :
            return View(model);
        }
        [HttpPost]
        public IActionResult RechercheDonMultiCri(DonRechercheViewModel model)
        {
            // récupérer le modele
            DonBusiness donBU = new DonBusiness();
            List<DonDetails> resultats = donBU.RechercheDonMultiCri(model.Nomcategorie, model.Nomsouscategorie, model.NomProduit, model.Nomville);
            

            // charger la vue :
            return View("Resultat", resultats);
        }
    }
}

WebApp2/Controllers/ReservationController.cs
using Fr.EQL.AI110.DLD_GE.Business;
using Fr.EQL.AI110.DLD_GE.Entities;
using Fr.EQL.AI110.DLD_GE.WebApp2.Models;
using Microsoft.AspNetCore.Mvc;

namespace Fr.EQL.AI110.DLD_GE.WebApp2.Controllers
{
    public class ReservationController : Controller
    {
        public IActionResult Index()
        {
            ReservationBusiness bu = new ReservationBusiness();
            List<ReservationDetails> list = new List<ReservationDetails>();
            list = bu.GetBasketsWithNbArticles();

            return View(list);
        }
        [HttpGet]
        public IActionResult AddBasket()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CatchDon(int idDon)
        {
            AddBasketViewModel model = new AddBasketViewModel();
            model.SelectedIdDon = idDon;

            AdherentBusiness bu = new AdherentBusiness();
            model.Adherents = bu.GetAdherents();

            return View("ChooseAdherent", model);
        }
        [HttpPost]
        public IActionResult AddBasket(AddBasketViewModel model)
        {
            ReservationBusiness reservationBusiness = new ReservationBusiness();

            Reservation reservation = new Reservation();
            reservation.DateAjoutPanier = DateTime.Now;

            reservationBusiness.SaveBasket(model.SelectedIdDon, model.ConnectedAdherent.Idadh, reservation.DateAjoutPanier);
            return RedirectToAction("DisplayBasket", new { id = model.ConnectedAdherent.Idadh });
        }
        public IActionResult DisplayBasket(int id)
        {
            ReservationBusiness bu = new ReservationBusiness();
            AdherentBusiness buAdh = new AdherentBusiness();

            ReservationViewModel model = new ReservationViewModel();
            model.DonsInBasket = bu.GetBasketByIdAdh(id);
            model.SelectedAdherent = buAdh.GetAdherentbyId(id);

            return View(model);
        }
        [HttpPost]
        public IActionResult MakeReservation(ReservationViewModel model)
        {
            ReservationBusiness bu = new ReservationBusiness();
            foreach (ReservationDetails r in bu.GetBasketByIdAdh(model.SelectedAdherent.Idadh))
            {
                bu.EditDateReservation(r.IdReservation, r.IdDon, r.IdAdh);
            }

            return RedirectToAction("Index");
        }
        [HttpPost]
        public IActionResult RemoveFromBasket(ReservationViewModel model)
        {
            ReservationBusiness bu = new ReservationBusiness();
            bu.DeleteDonInBasket(model.IdSelectedDonToRemove, model.SelectedAdherent.Idadh);

            return RedirectToAction("DisplayBasket", new { id = model.SelectedAdherent.Idadh });
        }
        public IActionResult DisplayReservation(int idAdh)
        {
            ReservationViewModel model = new ReservationViewModel();
            ReservationBusiness bu = new ReservationBusiness();
            AdherentBusiness adhBu = new AdherentBusiness();

            model.DonsInBasket = bu.GetAllReservationByIdAdh(idAdh);
            model.SelectedAdherent = adhBu.GetAdherentbyId(idAdh);

            return View(model);
        }
        public IActionResult DisplayAllAdherentsWithReservations()
        {
            ReservationBusiness bu = new ReservationBusiness();
            List<ReservationDetails> list = new List<ReservationDetails>();
            list = bu.GetReservationsWithNbArticles();

            return View(list);
        }
        [HttpPost]
        public IActionResult RemoveFromReservation(ReservationViewModel model)
        {
            ReservationBusiness bu = new ReservationBusiness();
            bu.EditDateAnnulation(model.IdSelectedDonToRemove);

            return RedirectToAction("DisplayReservation", new { idAdh = model.SelectedAdherent.Idadh });
        }
    }
}

WebApp2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - D.L.D.</title>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
</head>
<body>
    <header class="navbar">
        <div class="nav">
            <img src="/images/logo.png" class="brand-logo">
            <div class="nav-items">
                <div class="search">
                    <input type="text" class="search-box" placeholder="Quel produit?">
                    <button class="search-btn">Rechercher</button>
                    <a asp-controller="Recherche" asp-action="RechercheDonMultiCri">
                        <button class="search-btn advanced">Avancée</button>
                    </a>
                </div>
            </div>
            <div class="nav-basket-user">
                <a asp-controller="Reservation" asp-action="Index" class="basket-link">
                    <img src="/images/cart.png">
                </a>
                <div class="nav-connection-info">
                    <div>Non Connecté</div>
                    <div>0 coupon</div>
                </div>
                <a href="#" class="user-link">
                    <img src="/images/user.png"></i>
                </a>
            </div>
        </div>
    </header>
    <nav class="left-navbar">
        <ul class="dashboard">
            <li class="dashboard-item">
                <img src="/images/mainlogo.png" class="dashboard-logo">
                <a class="dashboard-link dashboard-text" asp-controller="Home" asp-action="Index"><h2 class="dashboard-title">Home</h2></a>
            </li>
        </ul>
        <ul class="dashboard">
            <li class="empty-item">
            </li>
            <li class="dashboard-item-title">
                <img src="/images/user.png" class="dashboard-logo">
                <h2 class="dashboard-title">Adherent</h2>
            </li>
            <li class="dashboard-item">
                <img src="/images/don.png" class="dashboard-logo">
                <a class="dashboard-link dashboard-text" asp-controller="Don" asp-action="Index">Mes Dons</a>
            </li>
            <li class="dashboard-item">
                <img src="/images/don.png" class="dashboard-logo">
                <a class="dashboard-link dashboard-text" asp-controller="Reservation" asp-action="DisplayAllAdherentsWithReservations">Mes Reservations</a>
            </li>
        </ul>
        <ul class="dashboard">
            <li class="empty-item">
            </li>
            <li class="dashboard-item-title">
                <img src="/images/partenaire.png" class="dashboard-logo">
                <h2 class="dashboard-title">Partenaire</h2>
            </li>
            <li class="dashboard-item">
                <img src="/images/infra.png" class="dashboard-logo">
                <a href="#" class="dashboard-link dashboard-text">Fonction 1</a>
            </li>
        </ul>
        <ul class="dashboard">
            <li class="empty-item">
            </li>
            <li class="dashboard-item-title">
                <img src="/images/admin.png" class="dashboard-logo">
                <h2 class="dashboard-title">Admin</h2>
            </li>
            <li class="dashboard-item">
                <img src="/images/partner.png" class="dashboard-logo">
                <a asp-controller="Partenaire" asp-action="IndexPartenaireParVille" class="dashboard-link dashboard-text">Mes Partenaires</a>
            </li>
        </ul>
        <ul class="about-contact">
            <li class="empty-item">
            </li>
            <li class="about-contact-item">
                <img src="/images/about.png" class="about-contact-logo">
                <a href="#" class="about-contact-link about-contact-text">A Propos</a>
            </li>
            <li class="about-contact-item">
                <img src="/images/contact.png" class="about-contact-logo">
                <a href="#" class="about-contact-link about-contact-text">Contact</a>
            </li>
        </ul>
    </nav>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>